//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace excel_tablice_projekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    

    public partial class tablicaEntities : DbContext
    {
        public tablicaEntities()
            : base("name=tablicaEntities")
        {
        }
           
    
        public virtual DbSet<Proizvod> Proizvod { get; set; }
    }
}
