//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace excel_tablice_projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvod
    {
        public int id { get; set; }
        public string NazivProizvoda { get; set; }
        public string SifraProizvoda { get; set; }
        public string MjernaJedinica { get; set; }
        public Nullable<int> Kolicina { get; set; }
    }
}
